### ISSUE TITLE
Is macOS Sonoma supported?

### ISSUE THREAD

**Issue by Atten007** [Ben216k/About-My-Mac#2]
Hello,

I want to install this app on my MacBook Air. It's running on macOS Sonoma (14.0). Unfortunately, idk whether this OS is supported or not in your application. If it's not supported, can you please make this app compatible with macOS Sonoma? This may be very nice!

Greetings,
Atten007 😄

**Comment by Ben216k** [comment]
This is planned, nothing finalized yet though! 
<img width="600" alt="Screenshot 2023-09-25 at 21 50 58" src="https://github.com/Ben216k/About-My-Mac/assets/91443760/73e1f739-bf0e-478e-a68a-4e436b1f5e00">

**Comment by Ben216k** [comment]
Solved with v1.0.0beta6
